/**
 * 내장 교과 영단어 문제풀
 * ARGong API 접근 불가 시 사용하는 폴백 데이터
 * 초등 3~6학년 교과서 기반 영단어
 */

const FallbackQuestions = {
    // 3학년
    "3": {
        "1": [
            { ID: 1, content: "hello", kor: "안녕", category: "word", Topic: "Greetings" },
            { ID: 2, content: "hi", kor: "안녕", category: "word", Topic: "Greetings" },
            { ID: 3, content: "bye", kor: "잘 가", category: "word", Topic: "Greetings" },
            { ID: 4, content: "good", kor: "좋은", category: "word", Topic: "Greetings" },
            { ID: 5, content: "morning", kor: "아침", category: "word", Topic: "Greetings" },
            { ID: 6, content: "name", kor: "이름", category: "word", Topic: "Greetings" },
            { ID: 7, content: "my", kor: "나의", category: "word", Topic: "Greetings" },
            { ID: 8, content: "your", kor: "너의", category: "word", Topic: "Greetings" },
            { ID: 9, content: "nice", kor: "좋은", category: "word", Topic: "Greetings" },
            { ID: 10, content: "meet", kor: "만나다", category: "word", Topic: "Greetings" },
            { ID: 11, content: "friend", kor: "친구", category: "word", Topic: "Greetings" },
            { ID: 12, content: "thank", kor: "감사하다", category: "word", Topic: "Greetings" }
        ],
        "2": [
            { ID: 13, content: "happy", kor: "행복한", category: "word", Topic: "Feelings" },
            { ID: 14, content: "sad", kor: "슬픈", category: "word", Topic: "Feelings" },
            { ID: 15, content: "angry", kor: "화난", category: "word", Topic: "Feelings" },
            { ID: 16, content: "fine", kor: "좋은", category: "word", Topic: "Feelings" },
            { ID: 17, content: "great", kor: "훌륭한", category: "word", Topic: "Feelings" },
            { ID: 18, content: "sorry", kor: "미안한", category: "word", Topic: "Feelings" },
            { ID: 19, content: "hungry", kor: "배고픈", category: "word", Topic: "Feelings" },
            { ID: 20, content: "tired", kor: "피곤한", category: "word", Topic: "Feelings" },
            { ID: 21, content: "scared", kor: "무서운", category: "word", Topic: "Feelings" },
            { ID: 22, content: "sick", kor: "아픈", category: "word", Topic: "Feelings" },
            { ID: 23, content: "sleepy", kor: "졸린", category: "word", Topic: "Feelings" },
            { ID: 24, content: "excited", kor: "신나는", category: "word", Topic: "Feelings" }
        ],
        "3": [
            { ID: 25, content: "one", kor: "하나", category: "word", Topic: "Numbers" },
            { ID: 26, content: "two", kor: "둘", category: "word", Topic: "Numbers" },
            { ID: 27, content: "three", kor: "셋", category: "word", Topic: "Numbers" },
            { ID: 28, content: "four", kor: "넷", category: "word", Topic: "Numbers" },
            { ID: 29, content: "five", kor: "다섯", category: "word", Topic: "Numbers" },
            { ID: 30, content: "six", kor: "여섯", category: "word", Topic: "Numbers" },
            { ID: 31, content: "seven", kor: "일곱", category: "word", Topic: "Numbers" },
            { ID: 32, content: "eight", kor: "여덟", category: "word", Topic: "Numbers" },
            { ID: 33, content: "nine", kor: "아홉", category: "word", Topic: "Numbers" },
            { ID: 34, content: "ten", kor: "열", category: "word", Topic: "Numbers" },
            { ID: 35, content: "count", kor: "세다", category: "word", Topic: "Numbers" },
            { ID: 36, content: "number", kor: "숫자", category: "word", Topic: "Numbers" }
        ],
        "4": [
            { ID: 37, content: "red", kor: "빨간", category: "word", Topic: "Colors" },
            { ID: 38, content: "blue", kor: "파란", category: "word", Topic: "Colors" },
            { ID: 39, content: "yellow", kor: "노란", category: "word", Topic: "Colors" },
            { ID: 40, content: "green", kor: "초록", category: "word", Topic: "Colors" },
            { ID: 41, content: "white", kor: "하얀", category: "word", Topic: "Colors" },
            { ID: 42, content: "black", kor: "검은", category: "word", Topic: "Colors" },
            { ID: 43, content: "orange", kor: "주황", category: "word", Topic: "Colors" },
            { ID: 44, content: "pink", kor: "분홍", category: "word", Topic: "Colors" },
            { ID: 45, content: "purple", kor: "보라", category: "word", Topic: "Colors" },
            { ID: 46, content: "brown", kor: "갈색", category: "word", Topic: "Colors" },
            { ID: 47, content: "color", kor: "색깔", category: "word", Topic: "Colors" },
            { ID: 48, content: "rainbow", kor: "무지개", category: "word", Topic: "Colors" }
        ],
        "5": [
            { ID: 49, content: "apple", kor: "사과", category: "word", Topic: "Fruits" },
            { ID: 50, content: "banana", kor: "바나나", category: "word", Topic: "Fruits" },
            { ID: 51, content: "grape", kor: "포도", category: "word", Topic: "Fruits" },
            { ID: 52, content: "orange", kor: "오렌지", category: "word", Topic: "Fruits" },
            { ID: 53, content: "peach", kor: "복숭아", category: "word", Topic: "Fruits" },
            { ID: 54, content: "melon", kor: "멜론", category: "word", Topic: "Fruits" },
            { ID: 55, content: "lemon", kor: "레몬", category: "word", Topic: "Fruits" },
            { ID: 56, content: "cherry", kor: "체리", category: "word", Topic: "Fruits" },
            { ID: 57, content: "mango", kor: "망고", category: "word", Topic: "Fruits" },
            { ID: 58, content: "fruit", kor: "과일", category: "word", Topic: "Fruits" },
            { ID: 59, content: "like", kor: "좋아하다", category: "word", Topic: "Fruits" },
            { ID: 60, content: "eat", kor: "먹다", category: "word", Topic: "Fruits" }
        ],
        "6": [
            { ID: 61, content: "dog", kor: "개", category: "word", Topic: "Animals" },
            { ID: 62, content: "cat", kor: "고양이", category: "word", Topic: "Animals" },
            { ID: 63, content: "bird", kor: "새", category: "word", Topic: "Animals" },
            { ID: 64, content: "fish", kor: "물고기", category: "word", Topic: "Animals" },
            { ID: 65, content: "rabbit", kor: "토끼", category: "word", Topic: "Animals" },
            { ID: 66, content: "bear", kor: "곰", category: "word", Topic: "Animals" },
            { ID: 67, content: "lion", kor: "사자", category: "word", Topic: "Animals" },
            { ID: 68, content: "tiger", kor: "호랑이", category: "word", Topic: "Animals" },
            { ID: 69, content: "monkey", kor: "원숭이", category: "word", Topic: "Animals" },
            { ID: 70, content: "elephant", kor: "코끼리", category: "word", Topic: "Animals" },
            { ID: 71, content: "animal", kor: "동물", category: "word", Topic: "Animals" },
            { ID: 72, content: "pet", kor: "애완동물", category: "word", Topic: "Animals" }
        ],
        "7": [
            { ID: 73, content: "book", kor: "책", category: "word", Topic: "School" },
            { ID: 74, content: "pencil", kor: "연필", category: "word", Topic: "School" },
            { ID: 75, content: "eraser", kor: "지우개", category: "word", Topic: "School" },
            { ID: 76, content: "ruler", kor: "자", category: "word", Topic: "School" },
            { ID: 77, content: "bag", kor: "가방", category: "word", Topic: "School" },
            { ID: 78, content: "desk", kor: "책상", category: "word", Topic: "School" },
            { ID: 79, content: "chair", kor: "의자", category: "word", Topic: "School" },
            { ID: 80, content: "teacher", kor: "선생님", category: "word", Topic: "School" },
            { ID: 81, content: "student", kor: "학생", category: "word", Topic: "School" },
            { ID: 82, content: "school", kor: "학교", category: "word", Topic: "School" },
            { ID: 83, content: "class", kor: "수업", category: "word", Topic: "School" },
            { ID: 84, content: "study", kor: "공부하다", category: "word", Topic: "School" }
        ],
        "8": [
            { ID: 85, content: "head", kor: "머리", category: "word", Topic: "Body" },
            { ID: 86, content: "eye", kor: "눈", category: "word", Topic: "Body" },
            { ID: 87, content: "nose", kor: "코", category: "word", Topic: "Body" },
            { ID: 88, content: "mouth", kor: "입", category: "word", Topic: "Body" },
            { ID: 89, content: "ear", kor: "귀", category: "word", Topic: "Body" },
            { ID: 90, content: "hand", kor: "손", category: "word", Topic: "Body" },
            { ID: 91, content: "foot", kor: "발", category: "word", Topic: "Body" },
            { ID: 92, content: "arm", kor: "팔", category: "word", Topic: "Body" },
            { ID: 93, content: "leg", kor: "다리", category: "word", Topic: "Body" },
            { ID: 94, content: "face", kor: "얼굴", category: "word", Topic: "Body" },
            { ID: 95, content: "body", kor: "몸", category: "word", Topic: "Body" },
            { ID: 96, content: "finger", kor: "손가락", category: "word", Topic: "Body" }
        ],
        "9": [
            { ID: 97, content: "mother", kor: "엄마", category: "word", Topic: "Family" },
            { ID: 98, content: "father", kor: "아빠", category: "word", Topic: "Family" },
            { ID: 99, content: "sister", kor: "언니/누나/여동생", category: "word", Topic: "Family" },
            { ID: 100, content: "brother", kor: "오빠/형/남동생", category: "word", Topic: "Family" },
            { ID: 101, content: "family", kor: "가족", category: "word", Topic: "Family" },
            { ID: 102, content: "baby", kor: "아기", category: "word", Topic: "Family" },
            { ID: 103, content: "grandma", kor: "할머니", category: "word", Topic: "Family" },
            { ID: 104, content: "grandpa", kor: "할아버지", category: "word", Topic: "Family" },
            { ID: 105, content: "love", kor: "사랑", category: "word", Topic: "Family" },
            { ID: 106, content: "home", kor: "집", category: "word", Topic: "Family" },
            { ID: 107, content: "together", kor: "함께", category: "word", Topic: "Family" },
            { ID: 108, content: "uncle", kor: "삼촌", category: "word", Topic: "Family" }
        ],
        "10": [
            { ID: 109, content: "big", kor: "큰", category: "word", Topic: "Adjectives" },
            { ID: 110, content: "small", kor: "작은", category: "word", Topic: "Adjectives" },
            { ID: 111, content: "long", kor: "긴", category: "word", Topic: "Adjectives" },
            { ID: 112, content: "short", kor: "짧은", category: "word", Topic: "Adjectives" },
            { ID: 113, content: "tall", kor: "키가 큰", category: "word", Topic: "Adjectives" },
            { ID: 114, content: "fast", kor: "빠른", category: "word", Topic: "Adjectives" },
            { ID: 115, content: "slow", kor: "느린", category: "word", Topic: "Adjectives" },
            { ID: 116, content: "hot", kor: "뜨거운", category: "word", Topic: "Adjectives" },
            { ID: 117, content: "cold", kor: "차가운", category: "word", Topic: "Adjectives" },
            { ID: 118, content: "new", kor: "새로운", category: "word", Topic: "Adjectives" },
            { ID: 119, content: "old", kor: "오래된", category: "word", Topic: "Adjectives" },
            { ID: 120, content: "pretty", kor: "예쁜", category: "word", Topic: "Adjectives" }
        ]
    },
    // 4학년
    "4": {
        "1": [
            { ID: 201, content: "spring", kor: "봄", category: "word", Topic: "Seasons" },
            { ID: 202, content: "summer", kor: "여름", category: "word", Topic: "Seasons" },
            { ID: 203, content: "fall", kor: "가을", category: "word", Topic: "Seasons" },
            { ID: 204, content: "winter", kor: "겨울", category: "word", Topic: "Seasons" },
            { ID: 205, content: "weather", kor: "날씨", category: "word", Topic: "Seasons" },
            { ID: 206, content: "sunny", kor: "맑은", category: "word", Topic: "Seasons" },
            { ID: 207, content: "cloudy", kor: "흐린", category: "word", Topic: "Seasons" },
            { ID: 208, content: "rainy", kor: "비 오는", category: "word", Topic: "Seasons" },
            { ID: 209, content: "snowy", kor: "눈 오는", category: "word", Topic: "Seasons" },
            { ID: 210, content: "windy", kor: "바람 부는", category: "word", Topic: "Seasons" },
            { ID: 211, content: "warm", kor: "따뜻한", category: "word", Topic: "Seasons" },
            { ID: 212, content: "cool", kor: "시원한", category: "word", Topic: "Seasons" }
        ],
        "2": [
            { ID: 213, content: "Monday", kor: "월요일", category: "word", Topic: "Days" },
            { ID: 214, content: "Tuesday", kor: "화요일", category: "word", Topic: "Days" },
            { ID: 215, content: "Wednesday", kor: "수요일", category: "word", Topic: "Days" },
            { ID: 216, content: "Thursday", kor: "목요일", category: "word", Topic: "Days" },
            { ID: 217, content: "Friday", kor: "금요일", category: "word", Topic: "Days" },
            { ID: 218, content: "Saturday", kor: "토요일", category: "word", Topic: "Days" },
            { ID: 219, content: "Sunday", kor: "일요일", category: "word", Topic: "Days" },
            { ID: 220, content: "today", kor: "오늘", category: "word", Topic: "Days" },
            { ID: 221, content: "tomorrow", kor: "내일", category: "word", Topic: "Days" },
            { ID: 222, content: "yesterday", kor: "어제", category: "word", Topic: "Days" },
            { ID: 223, content: "week", kor: "주", category: "word", Topic: "Days" },
            { ID: 224, content: "day", kor: "날", category: "word", Topic: "Days" }
        ],
        "3": [
            { ID: 225, content: "breakfast", kor: "아침 식사", category: "word", Topic: "Food" },
            { ID: 226, content: "lunch", kor: "점심", category: "word", Topic: "Food" },
            { ID: 227, content: "dinner", kor: "저녁 식사", category: "word", Topic: "Food" },
            { ID: 228, content: "rice", kor: "밥", category: "word", Topic: "Food" },
            { ID: 229, content: "bread", kor: "빵", category: "word", Topic: "Food" },
            { ID: 230, content: "milk", kor: "우유", category: "word", Topic: "Food" },
            { ID: 231, content: "water", kor: "물", category: "word", Topic: "Food" },
            { ID: 232, content: "juice", kor: "주스", category: "word", Topic: "Food" },
            { ID: 233, content: "egg", kor: "달걀", category: "word", Topic: "Food" },
            { ID: 234, content: "chicken", kor: "닭고기", category: "word", Topic: "Food" },
            { ID: 235, content: "cake", kor: "케이크", category: "word", Topic: "Food" },
            { ID: 236, content: "pizza", kor: "피자", category: "word", Topic: "Food" }
        ],
        "4": [
            { ID: 237, content: "park", kor: "공원", category: "word", Topic: "Places" },
            { ID: 238, content: "hospital", kor: "병원", category: "word", Topic: "Places" },
            { ID: 239, content: "library", kor: "도서관", category: "word", Topic: "Places" },
            { ID: 240, content: "store", kor: "가게", category: "word", Topic: "Places" },
            { ID: 241, content: "market", kor: "시장", category: "word", Topic: "Places" },
            { ID: 242, content: "station", kor: "역", category: "word", Topic: "Places" },
            { ID: 243, content: "bank", kor: "은행", category: "word", Topic: "Places" },
            { ID: 244, content: "museum", kor: "박물관", category: "word", Topic: "Places" },
            { ID: 245, content: "zoo", kor: "동물원", category: "word", Topic: "Places" },
            { ID: 246, content: "church", kor: "교회", category: "word", Topic: "Places" },
            { ID: 247, content: "restaurant", kor: "식당", category: "word", Topic: "Places" },
            { ID: 248, content: "street", kor: "거리", category: "word", Topic: "Places" }
        ],
        "5": [
            { ID: 249, content: "run", kor: "달리다", category: "word", Topic: "Actions" },
            { ID: 250, content: "jump", kor: "점프하다", category: "word", Topic: "Actions" },
            { ID: 251, content: "swim", kor: "수영하다", category: "word", Topic: "Actions" },
            { ID: 252, content: "sing", kor: "노래하다", category: "word", Topic: "Actions" },
            { ID: 253, content: "dance", kor: "춤추다", category: "word", Topic: "Actions" },
            { ID: 254, content: "read", kor: "읽다", category: "word", Topic: "Actions" },
            { ID: 255, content: "write", kor: "쓰다", category: "word", Topic: "Actions" },
            { ID: 256, content: "draw", kor: "그리다", category: "word", Topic: "Actions" },
            { ID: 257, content: "play", kor: "놀다", category: "word", Topic: "Actions" },
            { ID: 258, content: "cook", kor: "요리하다", category: "word", Topic: "Actions" },
            { ID: 259, content: "sleep", kor: "자다", category: "word", Topic: "Actions" },
            { ID: 260, content: "walk", kor: "걷다", category: "word", Topic: "Actions" }
        ],
        "6": [
            { ID: 261, content: "shirt", kor: "셔츠", category: "word", Topic: "Clothes" },
            { ID: 262, content: "pants", kor: "바지", category: "word", Topic: "Clothes" },
            { ID: 263, content: "shoes", kor: "신발", category: "word", Topic: "Clothes" },
            { ID: 264, content: "hat", kor: "모자", category: "word", Topic: "Clothes" },
            { ID: 265, content: "dress", kor: "원피스", category: "word", Topic: "Clothes" },
            { ID: 266, content: "jacket", kor: "자켓", category: "word", Topic: "Clothes" },
            { ID: 267, content: "socks", kor: "양말", category: "word", Topic: "Clothes" },
            { ID: 268, content: "skirt", kor: "치마", category: "word", Topic: "Clothes" },
            { ID: 269, content: "coat", kor: "코트", category: "word", Topic: "Clothes" },
            { ID: 270, content: "boots", kor: "부츠", category: "word", Topic: "Clothes" },
            { ID: 271, content: "gloves", kor: "장갑", category: "word", Topic: "Clothes" },
            { ID: 272, content: "scarf", kor: "목도리", category: "word", Topic: "Clothes" }
        ],
        "7": [
            { ID: 273, content: "clock", kor: "시계", category: "word", Topic: "Time" },
            { ID: 274, content: "time", kor: "시간", category: "word", Topic: "Time" },
            { ID: 275, content: "hour", kor: "시", category: "word", Topic: "Time" },
            { ID: 276, content: "minute", kor: "분", category: "word", Topic: "Time" },
            { ID: 277, content: "morning", kor: "아침", category: "word", Topic: "Time" },
            { ID: 278, content: "afternoon", kor: "오후", category: "word", Topic: "Time" },
            { ID: 279, content: "evening", kor: "저녁", category: "word", Topic: "Time" },
            { ID: 280, content: "night", kor: "밤", category: "word", Topic: "Time" },
            { ID: 281, content: "noon", kor: "정오", category: "word", Topic: "Time" },
            { ID: 282, content: "early", kor: "이른", category: "word", Topic: "Time" },
            { ID: 283, content: "late", kor: "늦은", category: "word", Topic: "Time" },
            { ID: 284, content: "always", kor: "항상", category: "word", Topic: "Time" }
        ],
        "8": [
            { ID: 285, content: "soccer", kor: "축구", category: "word", Topic: "Sports" },
            { ID: 286, content: "baseball", kor: "야구", category: "word", Topic: "Sports" },
            { ID: 287, content: "basketball", kor: "농구", category: "word", Topic: "Sports" },
            { ID: 288, content: "tennis", kor: "테니스", category: "word", Topic: "Sports" },
            { ID: 289, content: "swimming", kor: "수영", category: "word", Topic: "Sports" },
            { ID: 290, content: "skating", kor: "스케이팅", category: "word", Topic: "Sports" },
            { ID: 291, content: "skiing", kor: "스키", category: "word", Topic: "Sports" },
            { ID: 292, content: "ball", kor: "공", category: "word", Topic: "Sports" },
            { ID: 293, content: "team", kor: "팀", category: "word", Topic: "Sports" },
            { ID: 294, content: "game", kor: "경기", category: "word", Topic: "Sports" },
            { ID: 295, content: "win", kor: "이기다", category: "word", Topic: "Sports" },
            { ID: 296, content: "lose", kor: "지다", category: "word", Topic: "Sports" }
        ],
        "9": [
            { ID: 297, content: "bedroom", kor: "침실", category: "word", Topic: "House" },
            { ID: 298, content: "kitchen", kor: "부엌", category: "word", Topic: "House" },
            { ID: 299, content: "bathroom", kor: "화장실", category: "word", Topic: "House" },
            { ID: 300, content: "garden", kor: "정원", category: "word", Topic: "House" },
            { ID: 301, content: "door", kor: "문", category: "word", Topic: "House" },
            { ID: 302, content: "window", kor: "창문", category: "word", Topic: "House" },
            { ID: 303, content: "table", kor: "탁자", category: "word", Topic: "House" },
            { ID: 304, content: "bed", kor: "침대", category: "word", Topic: "House" },
            { ID: 305, content: "sofa", kor: "소파", category: "word", Topic: "House" },
            { ID: 306, content: "lamp", kor: "전등", category: "word", Topic: "House" },
            { ID: 307, content: "room", kor: "방", category: "word", Topic: "House" },
            { ID: 308, content: "floor", kor: "바닥", category: "word", Topic: "House" }
        ],
        "10": [
            { ID: 309, content: "January", kor: "1월", category: "word", Topic: "Months" },
            { ID: 310, content: "February", kor: "2월", category: "word", Topic: "Months" },
            { ID: 311, content: "March", kor: "3월", category: "word", Topic: "Months" },
            { ID: 312, content: "April", kor: "4월", category: "word", Topic: "Months" },
            { ID: 313, content: "May", kor: "5월", category: "word", Topic: "Months" },
            { ID: 314, content: "June", kor: "6월", category: "word", Topic: "Months" },
            { ID: 315, content: "July", kor: "7월", category: "word", Topic: "Months" },
            { ID: 316, content: "August", kor: "8월", category: "word", Topic: "Months" },
            { ID: 317, content: "September", kor: "9월", category: "word", Topic: "Months" },
            { ID: 318, content: "October", kor: "10월", category: "word", Topic: "Months" },
            { ID: 319, content: "November", kor: "11월", category: "word", Topic: "Months" },
            { ID: 320, content: "December", kor: "12월", category: "word", Topic: "Months" }
        ]
    },
    // 5학년
    "5": {
        "1": [
            { ID: 501, content: "country", kor: "나라", category: "word", Topic: "Countries" },
            { ID: 502, content: "Korea", kor: "한국", category: "word", Topic: "Countries" },
            { ID: 503, content: "America", kor: "미국", category: "word", Topic: "Countries" },
            { ID: 504, content: "China", kor: "중국", category: "word", Topic: "Countries" },
            { ID: 505, content: "Japan", kor: "일본", category: "word", Topic: "Countries" },
            { ID: 506, content: "England", kor: "영국", category: "word", Topic: "Countries" },
            { ID: 507, content: "France", kor: "프랑스", category: "word", Topic: "Countries" },
            { ID: 508, content: "world", kor: "세계", category: "word", Topic: "Countries" },
            { ID: 509, content: "travel", kor: "여행하다", category: "word", Topic: "Countries" },
            { ID: 510, content: "language", kor: "언어", category: "word", Topic: "Countries" },
            { ID: 511, content: "speak", kor: "말하다", category: "word", Topic: "Countries" },
            { ID: 512, content: "culture", kor: "문화", category: "word", Topic: "Countries" }
        ],
        "2": [
            { ID: 513, content: "birthday", kor: "생일", category: "word", Topic: "Celebration" },
            { ID: 514, content: "party", kor: "파티", category: "word", Topic: "Celebration" },
            { ID: 515, content: "present", kor: "선물", category: "word", Topic: "Celebration" },
            { ID: 516, content: "holiday", kor: "휴일", category: "word", Topic: "Celebration" },
            { ID: 517, content: "festival", kor: "축제", category: "word", Topic: "Celebration" },
            { ID: 518, content: "invite", kor: "초대하다", category: "word", Topic: "Celebration" },
            { ID: 519, content: "candle", kor: "초", category: "word", Topic: "Celebration" },
            { ID: 520, content: "balloon", kor: "풍선", category: "word", Topic: "Celebration" },
            { ID: 521, content: "wish", kor: "소원", category: "word", Topic: "Celebration" },
            { ID: 522, content: "celebrate", kor: "축하하다", category: "word", Topic: "Celebration" },
            { ID: 523, content: "card", kor: "카드", category: "word", Topic: "Celebration" },
            { ID: 524, content: "surprise", kor: "놀라움", category: "word", Topic: "Celebration" }
        ],
        "3": [
            { ID: 525, content: "mountain", kor: "산", category: "word", Topic: "Nature" },
            { ID: 526, content: "river", kor: "강", category: "word", Topic: "Nature" },
            { ID: 527, content: "ocean", kor: "바다", category: "word", Topic: "Nature" },
            { ID: 528, content: "forest", kor: "숲", category: "word", Topic: "Nature" },
            { ID: 529, content: "flower", kor: "꽃", category: "word", Topic: "Nature" },
            { ID: 530, content: "tree", kor: "나무", category: "word", Topic: "Nature" },
            { ID: 531, content: "sky", kor: "하늘", category: "word", Topic: "Nature" },
            { ID: 532, content: "star", kor: "별", category: "word", Topic: "Nature" },
            { ID: 533, content: "moon", kor: "달", category: "word", Topic: "Nature" },
            { ID: 534, content: "sun", kor: "태양", category: "word", Topic: "Nature" },
            { ID: 535, content: "cloud", kor: "구름", category: "word", Topic: "Nature" },
            { ID: 536, content: "rain", kor: "비", category: "word", Topic: "Nature" }
        ],
        "4": [
            { ID: 537, content: "doctor", kor: "의사", category: "word", Topic: "Jobs" },
            { ID: 538, content: "nurse", kor: "간호사", category: "word", Topic: "Jobs" },
            { ID: 539, content: "police", kor: "경찰", category: "word", Topic: "Jobs" },
            { ID: 540, content: "firefighter", kor: "소방관", category: "word", Topic: "Jobs" },
            { ID: 541, content: "pilot", kor: "조종사", category: "word", Topic: "Jobs" },
            { ID: 542, content: "farmer", kor: "농부", category: "word", Topic: "Jobs" },
            { ID: 543, content: "scientist", kor: "과학자", category: "word", Topic: "Jobs" },
            { ID: 544, content: "artist", kor: "예술가", category: "word", Topic: "Jobs" },
            { ID: 545, content: "singer", kor: "가수", category: "word", Topic: "Jobs" },
            { ID: 546, content: "driver", kor: "운전사", category: "word", Topic: "Jobs" },
            { ID: 547, content: "chef", kor: "요리사", category: "word", Topic: "Jobs" },
            { ID: 548, content: "dream", kor: "꿈", category: "word", Topic: "Jobs" }
        ],
        "5": [
            { ID: 549, content: "computer", kor: "컴퓨터", category: "word", Topic: "Technology" },
            { ID: 550, content: "phone", kor: "전화기", category: "word", Topic: "Technology" },
            { ID: 551, content: "internet", kor: "인터넷", category: "word", Topic: "Technology" },
            { ID: 552, content: "camera", kor: "카메라", category: "word", Topic: "Technology" },
            { ID: 553, content: "robot", kor: "로봇", category: "word", Topic: "Technology" },
            { ID: 554, content: "screen", kor: "화면", category: "word", Topic: "Technology" },
            { ID: 555, content: "keyboard", kor: "키보드", category: "word", Topic: "Technology" },
            { ID: 556, content: "mouse", kor: "마우스", category: "word", Topic: "Technology" },
            { ID: 557, content: "video", kor: "영상", category: "word", Topic: "Technology" },
            { ID: 558, content: "email", kor: "이메일", category: "word", Topic: "Technology" },
            { ID: 559, content: "search", kor: "검색하다", category: "word", Topic: "Technology" },
            { ID: 560, content: "click", kor: "클릭하다", category: "word", Topic: "Technology" }
        ],
        "6": [
            { ID: 561, content: "subject", kor: "과목", category: "word", Topic: "Subjects" },
            { ID: 562, content: "math", kor: "수학", category: "word", Topic: "Subjects" },
            { ID: 563, content: "science", kor: "과학", category: "word", Topic: "Subjects" },
            { ID: 564, content: "English", kor: "영어", category: "word", Topic: "Subjects" },
            { ID: 565, content: "music", kor: "음악", category: "word", Topic: "Subjects" },
            { ID: 566, content: "art", kor: "미술", category: "word", Topic: "Subjects" },
            { ID: 567, content: "history", kor: "역사", category: "word", Topic: "Subjects" },
            { ID: 568, content: "favorite", kor: "가장 좋아하는", category: "word", Topic: "Subjects" },
            { ID: 569, content: "homework", kor: "숙제", category: "word", Topic: "Subjects" },
            { ID: 570, content: "test", kor: "시험", category: "word", Topic: "Subjects" },
            { ID: 571, content: "answer", kor: "답", category: "word", Topic: "Subjects" },
            { ID: 572, content: "question", kor: "질문", category: "word", Topic: "Subjects" }
        ]
    },
    // 6학년
    "6": {
        "1": [
            { ID: 601, content: "vacation", kor: "방학", category: "word", Topic: "Travel" },
            { ID: 602, content: "airport", kor: "공항", category: "word", Topic: "Travel" },
            { ID: 603, content: "passport", kor: "여권", category: "word", Topic: "Travel" },
            { ID: 604, content: "ticket", kor: "표", category: "word", Topic: "Travel" },
            { ID: 605, content: "hotel", kor: "호텔", category: "word", Topic: "Travel" },
            { ID: 606, content: "beach", kor: "해변", category: "word", Topic: "Travel" },
            { ID: 607, content: "visit", kor: "방문하다", category: "word", Topic: "Travel" },
            { ID: 608, content: "trip", kor: "여행", category: "word", Topic: "Travel" },
            { ID: 609, content: "map", kor: "지도", category: "word", Topic: "Travel" },
            { ID: 610, content: "luggage", kor: "짐", category: "word", Topic: "Travel" },
            { ID: 611, content: "adventure", kor: "모험", category: "word", Topic: "Travel" },
            { ID: 612, content: "explore", kor: "탐험하다", category: "word", Topic: "Travel" }
        ],
        "2": [
            { ID: 613, content: "environment", kor: "환경", category: "word", Topic: "Environment" },
            { ID: 614, content: "recycle", kor: "재활용하다", category: "word", Topic: "Environment" },
            { ID: 615, content: "energy", kor: "에너지", category: "word", Topic: "Environment" },
            { ID: 616, content: "pollution", kor: "오염", category: "word", Topic: "Environment" },
            { ID: 617, content: "earth", kor: "지구", category: "word", Topic: "Environment" },
            { ID: 618, content: "nature", kor: "자연", category: "word", Topic: "Environment" },
            { ID: 619, content: "protect", kor: "보호하다", category: "word", Topic: "Environment" },
            { ID: 620, content: "clean", kor: "깨끗한", category: "word", Topic: "Environment" },
            { ID: 621, content: "trash", kor: "쓰레기", category: "word", Topic: "Environment" },
            { ID: 622, content: "save", kor: "절약하다", category: "word", Topic: "Environment" },
            { ID: 623, content: "planet", kor: "행성", category: "word", Topic: "Environment" },
            { ID: 624, content: "future", kor: "미래", category: "word", Topic: "Environment" }
        ],
        "3": [
            { ID: 625, content: "healthy", kor: "건강한", category: "word", Topic: "Health" },
            { ID: 626, content: "exercise", kor: "운동", category: "word", Topic: "Health" },
            { ID: 627, content: "vegetable", kor: "채소", category: "word", Topic: "Health" },
            { ID: 628, content: "medicine", kor: "약", category: "word", Topic: "Health" },
            { ID: 629, content: "headache", kor: "두통", category: "word", Topic: "Health" },
            { ID: 630, content: "stomachache", kor: "복통", category: "word", Topic: "Health" },
            { ID: 631, content: "fever", kor: "열", category: "word", Topic: "Health" },
            { ID: 632, content: "cough", kor: "기침", category: "word", Topic: "Health" },
            { ID: 633, content: "sneeze", kor: "재채기", category: "word", Topic: "Health" },
            { ID: 634, content: "strong", kor: "강한", category: "word", Topic: "Health" },
            { ID: 635, content: "weak", kor: "약한", category: "word", Topic: "Health" },
            { ID: 636, content: "rest", kor: "쉬다", category: "word", Topic: "Health" }
        ],
        "4": [
            { ID: 637, content: "shopping", kor: "쇼핑", category: "word", Topic: "Shopping" },
            { ID: 638, content: "money", kor: "돈", category: "word", Topic: "Shopping" },
            { ID: 639, content: "price", kor: "가격", category: "word", Topic: "Shopping" },
            { ID: 640, content: "cheap", kor: "싼", category: "word", Topic: "Shopping" },
            { ID: 641, content: "expensive", kor: "비싼", category: "word", Topic: "Shopping" },
            { ID: 642, content: "buy", kor: "사다", category: "word", Topic: "Shopping" },
            { ID: 643, content: "sell", kor: "팔다", category: "word", Topic: "Shopping" },
            { ID: 644, content: "change", kor: "거스름돈", category: "word", Topic: "Shopping" },
            { ID: 645, content: "dollar", kor: "달러", category: "word", Topic: "Shopping" },
            { ID: 646, content: "coin", kor: "동전", category: "word", Topic: "Shopping" },
            { ID: 647, content: "pay", kor: "지불하다", category: "word", Topic: "Shopping" },
            { ID: 648, content: "receipt", kor: "영수증", category: "word", Topic: "Shopping" }
        ],
        "5": [
            { ID: 649, content: "movie", kor: "영화", category: "word", Topic: "Entertainment" },
            { ID: 650, content: "theater", kor: "극장", category: "word", Topic: "Entertainment" },
            { ID: 651, content: "concert", kor: "콘서트", category: "word", Topic: "Entertainment" },
            { ID: 652, content: "hobby", kor: "취미", category: "word", Topic: "Entertainment" },
            { ID: 653, content: "guitar", kor: "기타", category: "word", Topic: "Entertainment" },
            { ID: 654, content: "piano", kor: "피아노", category: "word", Topic: "Entertainment" },
            { ID: 655, content: "painting", kor: "그림", category: "word", Topic: "Entertainment" },
            { ID: 656, content: "reading", kor: "독서", category: "word", Topic: "Entertainment" },
            { ID: 657, content: "camping", kor: "캠핑", category: "word", Topic: "Entertainment" },
            { ID: 658, content: "fishing", kor: "낚시", category: "word", Topic: "Entertainment" },
            { ID: 659, content: "enjoy", kor: "즐기다", category: "word", Topic: "Entertainment" },
            { ID: 660, content: "fun", kor: "재미있는", category: "word", Topic: "Entertainment" }
        ],
        "6": [
            { ID: 661, content: "important", kor: "중요한", category: "word", Topic: "Values" },
            { ID: 662, content: "kind", kor: "친절한", category: "word", Topic: "Values" },
            { ID: 663, content: "honest", kor: "정직한", category: "word", Topic: "Values" },
            { ID: 664, content: "brave", kor: "용감한", category: "word", Topic: "Values" },
            { ID: 665, content: "patient", kor: "참을성 있는", category: "word", Topic: "Values" },
            { ID: 666, content: "polite", kor: "예의 바른", category: "word", Topic: "Values" },
            { ID: 667, content: "respect", kor: "존경하다", category: "word", Topic: "Values" },
            { ID: 668, content: "share", kor: "나누다", category: "word", Topic: "Values" },
            { ID: 669, content: "help", kor: "돕다", category: "word", Topic: "Values" },
            { ID: 670, content: "believe", kor: "믿다", category: "word", Topic: "Values" },
            { ID: 671, content: "trust", kor: "신뢰하다", category: "word", Topic: "Values" },
            { ID: 672, content: "promise", kor: "약속", category: "word", Topic: "Values" }
        ]
    }
};

window.FallbackQuestions = FallbackQuestions;
